// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVQF_Xx99PvRiXP0COdyubEp99xYrxpV8',
    appId: '1:939586059696:web:cfd1ded0cfa45ea4196a75',
    messagingSenderId: '939586059696',
    projectId: 'studytree-c9ad8',
    authDomain: 'studytree-c9ad8.firebaseapp.com',
    storageBucket: 'studytree-c9ad8.firebasestorage.app',
    measurementId: 'G-7CDBTNX09B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs8vLUoMbMEWhEhgdDppolqoo7g9gjHQE',
    appId: '1:939586059696:android:42bfaacfdf70f9f5196a75',
    messagingSenderId: '939586059696',
    projectId: 'studytree-c9ad8',
    storageBucket: 'studytree-c9ad8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7Ya8nJIRcOAd79o3R_rj1T5nK6GZbmSc',
    appId: '1:939586059696:ios:be02ac8d5fabade0196a75',
    messagingSenderId: '939586059696',
    projectId: 'studytree-c9ad8',
    storageBucket: 'studytree-c9ad8.firebasestorage.app',
    iosBundleId: 'com.example.studyTree',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7Ya8nJIRcOAd79o3R_rj1T5nK6GZbmSc',
    appId: '1:939586059696:ios:be02ac8d5fabade0196a75',
    messagingSenderId: '939586059696',
    projectId: 'studytree-c9ad8',
    storageBucket: 'studytree-c9ad8.firebasestorage.app',
    iosBundleId: 'com.example.studyTree',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVQF_Xx99PvRiXP0COdyubEp99xYrxpV8',
    appId: '1:939586059696:web:4452de8c6bfca5b1196a75',
    messagingSenderId: '939586059696',
    projectId: 'studytree-c9ad8',
    authDomain: 'studytree-c9ad8.firebaseapp.com',
    storageBucket: 'studytree-c9ad8.firebasestorage.app',
    measurementId: 'G-H88XNDB7R6',
  );
}
